stages:
  - build
  - test
  - package
  - doc


before_script:
  - cd game_library_ci 
build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - game_library_ci/target/site/jacoco/index.html
      - rspec.xml
    reports:
      junit: rspec.xml
     
package:
  stage: package
  script:
    - mvn package

doc:
  stage: doc
  script:
    - mvn javadoc:javadoc

