stages:
  - build
  - test
  - package
  - doc


before_script:
  - cd game_library_ci 
build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

doc:
  stage: doc
  script:
    - mvn javadoc:javadoc

