stages:
  - build
  - test
  - package
  - doc
  - check

build:
  stage: build
  script:
    - make build 

test:
  stage: test
  script:
    - tthor/test 

package:
  stage: package
  script:
    - make package

doc:
  stage: doc
  script:
    - make doc

check:
  stage: check
  script:
    - make check
